services:
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
  cache:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    expose:
      - "6379"
